API Tests: Added pause for stack startup.
To reduce test flakiness.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -15,11 +15,17 @@ jobs:
       - name: Setup running platform stack
         run: docker compose up --build -d
 
+      - name: Pause for stack to start
+        run: sleep 10
+
       - name: Integration tests - API
         run: docker run 
           --env CONF_DIR=/dp3/tests/test_config 
           --network container:dp3_api 
           dp3_interpreter python -m unittest discover -s tests/test_api -v
+
+      - name: Check worker errors
+        run: docker compose logs worker | grep "WARNING\|ERROR\|exception" | grep -v "RabbitMQ\|it's\ OK\ now,\ we're\ successfully\ connected" || true
 
       - name: Teardown platform stack
         run: docker compose down
